
# Kitty Configuration

# -------------------------------------------------------------------------------------------------------------------- #

# Font

font_family      IosevkaNerdFontCompleteM-Bold
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

# -------------------------------------------------------------------------------------------------------------------- #

# Cursor

cursor_shape block
shell_integration  no-cursor

# -------------------------------------------------------------------------------------------------------------------- #

# Scroll

scrollback_lines 1000000

# -------------------------------------------------------------------------------------------------------------------- #

# Layout Options

enabled_layouts grid

# Split vertical (side-by-side)
map alt+v launch --location=vsplit

# Split horizontal (top-bottom)
map alt+s launch --location=hsplit

# Navigate between splits
map alt+h neighboring_window left
map alt+j neighboring_window down
map alt+k neighboring_window up
map alt+l neighboring_window right

# -------------------------------------------------------------------------------------------------------------------- #
# BEGIN_KITTY_THEME
# Alabaster
include current-theme.conf
# END_KITTY_THEME
