# ------------------------------
# Prompt Layout
# ------------------------------
format = """
$cmd_duration\
$time\
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$docker_context\
\r
$character\
"""

[line_break]
disabled = false

# ------------------------------
# Command Duration
# ------------------------------
[cmd_duration]
min_time = 1000
format = "Took [$duration](#6272a4)\n\n"

# ------------------------------
# Time
# ------------------------------
[time]
disabled = false
time_format = "%R"
style = "bg:#6272a4 bold fg:#ffffff"
format = '[](fg:#6272a4)[  $time ]($style)[](fg:#6272a4 bg:none)'

# ------------------------------
# OS
# ------------------------------
[os]
style = "bg:blue bold fg:#ffffff"
format = '[](inverted fg:blue)[ $symbol]($style)'
disabled = false

[os.symbols]
Debian = " "
Fedora = " "
Macos = " "
Ubuntu = " "
Unknown = "❓ "
Windows = " "

# ------------------------------
# User
# ------------------------------
[username]
show_always = true
style_user = "bg:blue bold fg:#ffffff"
style_root = "bg:blue bold fg:#ffffff"
format = '[$user ]($style)[](fg:blue bg:none)'
disabled = false

# ------------------------------
# Directory
# ------------------------------
[directory]
style = "bg:#f4d03f bold fg:#000000"
read_only = " "
format = '[ ](inverted fg:#f4d03f)[$read_only]($style)[$path ]($style)[](fg:#f4d03f bg:none)'
truncation_length = 10
truncate_to_repo = false
truncation_symbol = "…/"

# ------------------------------
# Git
# ------------------------------
[git_branch]
symbol = ""
style = "bg:cyan bold fg:#ffffff"
format = '[](inverted fg:cyan)[ $symbol $branch ]($style)'

[git_commit]
style = "bg:cyan bold fg:#ffffff"
format = '[($hash$tag)]($style)'
only_detached = true

[git_status]
style = "bg:cyan bold fg:#ffffff"
format = '[ $stashed]($style)[](fg:cyan bg:none)'

# ------------------------------
# Python
# ------------------------------
[python]
symbol = "  "
style = "bg:#4c566a bold fg:#ffffff"
format = '[](inverted fg:#4c566a)[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)[](fg:#4c566a bg:none)'

# ------------------------------
# Docker
# ------------------------------
[docker_context]
symbol = " "
style = "bg:#5e81ac"
format = '[](inverted fg:#4c566a)[ $symbol $context ]($style) $path [](fg:#4c566a bg:none)'

# ------------------------------
# C
# ------------------------------
[c]
symbol = " "
style = "bg:#4c566a bold fg:#ffffff"
format = '[](inverted fg:#4c566a)[ $symbol ($version) ]($style)[](fg:#4c566a bg:none)'

# ------------------------------
# Rust
# ------------------------------
[rust]
symbol = ""
style = "bg:cyan"
format = '[ $symbol ($version) ]($style)'

# ------------------------------
# Prompt Character
# ------------------------------
[character]
success_symbol = '[❯](#6272a4)'
error_symbol = '[❯](bold red)'
